
server:
servlet:
context-path: /

#github的id，密钥，和重定向url
github.setClient_id: b9225f6945ef5e6c3aa3
github.setClient_secret: 867be0b43cb1c39de7473c8d4e1879294ba3edbc
github.setRedirect_uri: http://localhost:8080/callback

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&servetTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlDataSource
  flyway:
    baseline-on-migrate: true




mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mapper/*.xml

