
server:
servlet:
context-path: /

#github的id，密钥，和重定向url
github.setClient_id: b9225f6945ef5e6c3aa3
github.setClient_secret: 867be0b43cb1c39de7473c8d4e1879294ba3edbc
github.setRedirect_uri: http://localhost:8080/callback

